### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by SB-SVM** [stevelittlefish/flaskfilemanager#1]
How can I change the configuration of the flaskfilemanager? E.g. I want to set the default view from grid view to list view.

(Thanks for the great implementation of the Rich File Manager in Flask! ;))

**Comment by stevelittlefish** [comment]
I've just pushed out a new version (0.0.6) to github and pypi which will help solve your problem.  Update your application to use the latest version and do the following:

You will need to create a custom filemanager.config.json file, and then pass the path of that file into flaskfilemanager.init() for example if you put it in the static directory of your flask app you could do:

```
config_json_path = os.path.join(app.root_path, 'static/filemanager.config.json')
flaskfilemanager.init(app, custom_config_json_path=config_json_path)
```
You're best off copying the config file from the repository here: https://github.com/stevelittlefish/flaskfilemanager/blob/master/flaskfilemanager/RichFilemanager/config/filemanager.config.json

In the config file if you search for `"defaultViewMode": "grid",` you can change that variable to "list".

Let me know if this works for you!

**Comment by SB-SVM** [comment]
Great, thanks, everything works perfectly!
